#!/usr/bin/env bash
# Build Magpie.app from the SPM executable.
# Usage: ./build.sh [--run]
set -euo pipefail

cd "$(dirname "$0")"

APP_NAME="Magpie"
BUNDLE_ID="com.hamzas.magpie"
APP_DIR="build/${APP_NAME}.app"
CONTENTS="${APP_DIR}/Contents"
MACOS="${CONTENTS}/MacOS"
RESOURCES="${CONTENTS}/Resources"

echo "→ swift build (release)"
swift build -c release

echo "→ assembling ${APP_DIR}"
rm -rf "${APP_DIR}"
mkdir -p "${MACOS}" "${RESOURCES}"

cp ".build/release/${APP_NAME}" "${MACOS}/${APP_NAME}"

# Optional app icon (.icns) — generated by tools/make_icon.sh if present.
if [[ -f "tools/Magpie.icns" ]]; then
    cp "tools/Magpie.icns" "${RESOURCES}/Magpie.icns"
    ICON_KEY='<key>CFBundleIconFile</key><string>Magpie</string>'
else
    ICON_KEY=''
fi

cat > "${CONTENTS}/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key><string>${APP_NAME}</string>
    <key>CFBundleIdentifier</key><string>${BUNDLE_ID}</string>
    <key>CFBundleName</key><string>${APP_NAME}</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>CFBundleShortVersionString</key><string>0.2</string>
    <key>CFBundleVersion</key><string>1</string>
    <key>LSMinimumSystemVersion</key><string>13.0</string>
    <key>LSUIElement</key><true/>
    <key>NSHighResolutionCapable</key><true/>
    ${ICON_KEY}
</dict>
</plist>
PLIST

echo "→ ad-hoc codesigning (Gatekeeper still won't trust it, but prevents 'is damaged' error)"
codesign --force --deep --sign - "${APP_DIR}" 2>&1 | tail -3

echo "→ done: ${APP_DIR}"

if [[ "${1:-}" == "--run" ]]; then
    echo "→ launching"
    pkill -x "${APP_NAME}" 2>/dev/null || true
    open "${APP_DIR}"
fi
